name: Release

on:
    workflow_dispatch:
        inputs:
            tag:
                type: string
            python_version:
                type: string
                default: "3.11"
            poetry_version:
                type: string
                default: "1.5.1"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: ncipollo/release-action@v1
              with:
                tag: "${{ github.event.inputs.tag }}"
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ github.event.inputs.python_version }}
            - uses: abatilo/actions-poetry@v2
              with:
                poetry-version: ${{ github.event.inputs.poetry_version }}
            - name: View Python version
              run: python --version
            - name: View poetry version
              run: poetry version
